### ISSUE TITLE
Tikz not rendering in the github page

### ISSUE THREAD

**Issue by durandg12** [computorg/computo-quarto-extension#37]
My submission is published as a GitHub page at this URL: https://durandg12.github.io/algo-curve/

The tikz figures are not rendered, tikz code is displayed instead, in both HTML and PDF.

On my computer, rendering produces the right figures in both HTML and PDF.

To my knowledge, I am using the last version of the build.yml workflow configuration file, as per discussed here : https://github.com/computorg/computo-quarto-extension/issues/33#issuecomment-2517565167 : 

```
name: Main Workflows

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  call_env_workflow:
    uses: computorg/workflows/.github/workflows/global-env.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      config-path: './config/quarto_config.yml'
  call_quartopublish_workflow:
    uses: computorg/workflows/.github/workflows/publish-render.yml@main
    needs: call_env_workflow
    with:
      config-path: './config/quarto_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
```

The actions are successfull after each push : https://github.com/durandg12/algo-curve/actions

Thanks in advance
