### ISSUE TITLE
Failed to generate bibliography

### ISSUE THREAD

**Issue by williamlorder** [computorg/computo-quarto-extension#4]
Thank you for making such an excellent template, however I found that the examples did not work with bibliography...

```shell
[WARNING] Could not highlight code block:
  Capture 2 not defined!
ERROR: Failed to generate bibliography, rendering failed with code 1
pandoc: /Users/zekai/Desktop/ed/Users/zekai/Desktop/ed/references.bib: openBinaryFile: does not exist (No such file or directory)
```

This is the original setup
```yaml
title: "Computo Journal Format"
subtitle: "To be used as template for contribution to Computo"
date: last-modified
author:
  - name: The Computo Team
    corresponding: true
    email: computo@sfds.asso.fr
    url: https://computo.sfds.asso.fr
    orcid: 0000-0000-0000-0000
    affiliations:
      - name: Société Française de Statistique
        department: Statistique
        address: IHP
        city: Paris
        country: France
        postal-code: 75005
  - name: a friend
    affiliations:
      - Another Affiliation
description: |
  This document provides a template based on the quarto system for contributions to Computo. The github repository in itself provides a specific quarto extension useful for authors (and editors!).
abstract: |
  This is the abstract - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur posuere vestibulum facilisis. Aenean pretium orci augue, quis lobortis libero accumsan eu. Nam mollis lorem sit amet pellentesque ullamcorper. Curabitur lobortis libero eget malesuada vestibulum. Nam nec nibh massa. Pellentesque porttitor cursus tellus. Mauris urna erat, rhoncus sed faucibus sit amet, venenatis eu ipsum.
keywords: [template, quarto, R, Python, reproductibility]
doi: 10.xxxx/xxx-xxx
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.xxxx/xxx-xxx"
  url: "https://github.com/computorg/computo-quarto-extension"
  issn: "2824-7795"
bibliography: references.bib
google-scholar: true
github-user: computorg
repo: "computo-quarto-extension"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
format:
  computo-html: default
  computo-pdf: default
```

**Comment by fradav** [comment]
I guess this a bug with quarto: https://github.com/quarto-dev/quarto-cli/issues/2851
Fixed with v1.2.215

@jchiquet we should mention it in the README something like: 
Quarto itself is a work-in-progress and a lot of bugs are constantly fixed or features added. As such, we recommend:
- searching any encountered issue with renders in the upstream quarto dev repo https://github.com/quarto-dev/quarto-cli/issues
- using the latest preview version of quarto in https://github.com/quarto-dev/quarto-cli/releases

**Comment by williamlorder** [comment]
Well,The problem was solved after updating to the lastest version.However, another issue arose when I render with my own bibliography file... That file was automatically generated from Zotero plugin _Better Bibtex_. Here is the error.

```shell
ERROR: TypeError: Cannot read properties of undefined (reading 'map')
```

and this is my setup.
```yaml
---
title: "A tremendous shock? — Understanding the secondary social impact of COVID-19 of people with disabilitie"
subtitle: "the secondary social impact of people with disabilities"
date: last-modified
author:
  - name: Zekai Lu
    corresponding: true
    email: 1903500028@e.gzhu.edu.cn
    url: https://computo.sfds.asso.fr
    orcid: 0000-0000-0000-0000
    affiliations: 
      - id: GZHU
        name: Guangzhou University
        department: Sociology
        address: No.230 Waihuanxi Lu
        city: Guangzhou
        state: Guangdong
        postal-code: 510440
description: |
  This document provides a template based on the quarto system for contributions to Computo. The github repository in itself provides a specific quarto extension useful for authors (and editors!).
keywords: [people with disabilities, COVID-19, secondary social impact, Intersectionality perspective, the ICF Framework]
doi: 10.xxxx/xxx-xxx
# citation:
#   type: article-journal
#   container-title: "Computo"
#   doi: "10.xxxx/xxx-xxx"
#   url: "https://github.com/computorg/computo-quarto-extension"
#   issn: "2824-7795"
google-scholar: true
github-user: computorg
repo: "computo-quarto-extension"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
bibliography: "references.bib"
filters: 
  - "/Users/zekai/lua/zotero.lua"
  - "/Users/zekai/lua/abstract-section.lua"
format:
  computo-html: default
  computo-pdf: default
---
```
